### ISSUE TITLE
Signature key - 

### ISSUE THREAD

**Issue by elsbrock** [kurthuwig/docker-duply#1]
Hi,

thank you for this repository. We are using it as a base for our backups. We have extended it slightly in order to support a master config that is shared by all duply profiles:

```
https://github.com/raumzeitlabor/backup-docker
```

I have noticed that by default, you're creating a PGP key with subkey. With this setup, we are unable to restore and get the following error:

```
root@c5b27c4806bc:/# duply mediawiki restore /tmp/foo                           
Start duply v1.5.10, time is 2015-06-21 17:09:39.                               
Using profile '/etc/duply/mediawiki'.                                           
Using installed duplicity version 0.6.23, python 2.7.6, gpg 1.4.16 (Home: /etc/duply/gnupg), awk 'mawk 1.3.3 Nov 1996, Copyright (C) Michael D. Brennan', bash '4.3.11(1)-release (x86_64-pc-linux-gnu)'.
Autoset found secret key of first GPG_KEY entry 'F7928C87' for signing.         
Test - Encrypt to F7928C87 & Sign with F7928C87 (OK)                            
Test - Decrypt (OK)                                                             
Test - Compare (OK)                                                             
Cleanup - Delete '/tmp/duply.797.1434899379_*'(OK)                              

--- Start running command RESTORE at 17:09:39.949 ---                           
Local and Remote metadata are synchronized, no sync needed.                     
Last full backup date: Sun Jun 21 16:56:23 2015                                 
Volume was signed by key A095D562, not F7928C87                                 
17:10:36.808 Task 'RESTORE' failed with exit code '22'.                         
--- Finished state FAILED 'code 22' at 17:10:36.808 - Runtime 00:00:56.858 ---
```

It looks like the archives are signed by the sub key, but duplicity expects it to be signed with another key. We were able to workaround this by not generating the subkey and thus signing with the encryption key.

Have you run into this problem?

Regards
Simon

**Comment by kurthuwig** [comment]
Hallo Simon,

war leider etwas im Stress, aber jetzt hab ich Urlaub. Das beschriebene
Problem hatte ich nicht. Duply unterstützt zwei Schlüssel: einen zum
Signieren und einen zum Verschlüsseln. Das nutzen wir, indem wir bei dem
Verschlüsselungs-Schlüssel den Private-Key nicht auf dem Server liegen
haben. Damit kann das Backup erstellt und verifiziert werden. Aber es kann
nicht zurück gelesen werden. Sollte ein Angreifer kommen, kann er nur unser
Backup löschen, aber nicht alte Backups lesen. Auf dem Ziel-Server wird das
ganze Read-Only gemacht, so dass das mit dem Löschen auch nicht mehr geht.

Warum hast du eigentlich ein neues Repo gemacht, statt meines zu forken und
darauf zu entwickeln? So ist es etwas schwieriger, die Änderungen bei mir
einzubauen.

Viele Grüße

Kurt

2015-06-21 18:41 GMT+02:00 Simon Elsbrock notifications@github.com:
