### ISSUE TITLE
Missing python-boto for using Duply with S3

### ISSUE THREAD

**Issue by shurik239** [kurthuwig/docker-duply#4]
Without it running "default backup" produce error 
"BackendException: Could not initialize backend: No module named boto"

**Comment by shurik239** [comment]
To make it work also with s3 RUN command in Dockerfile schould be extended like this:
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    duply \
    ncftp \
    pwgen \
    python-pip \
    && rm -rf /var/lib/apt/lists/\* /var/cache/apt/\* \
    && pip install boto

**Comment by kurthuwig** [comment]
Hi shurik239,

thanks for the heads up. Does the Ubuntu package "python-boto" is sufficient or do I have to install it from the Python archives for it to work?

Happy new year!

Kurt

**Comment by shurik239** [comment]
Hallo Kurt,

just install python-boto did not work for me. 

Freues neues!

Gruß,
Alexander
